### ISSUE TITLE
Add hostname target

### ISSUE THREAD

**Issue by jhriv** [jhriv/vagrant-as-infrastructure#27]
## Expected Behavior

A guest can set its own hostname via Makefile target

## Actual Behavior

Nope.

## Steps to Reproduce the Problem

1. make all
2. make hostname
3. fail

## Specifications

- Version: current
- Platform: all 
- Make version: irrelevant
- Vagrant version: irrelevant
- VirtualBox version: irrelevant

## Additional Notes:

There's an `etc-hosts` target. Why not `hostname`?

**Comment by jhriv** [comment]
```yaml
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'
      become: true
```

How hard is this?
